global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'my_service'
    static_configs:
      - targets: ['my_service:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
